version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine 
    container_name: babylonian_db
    restart: always 
    
    environment:
      POSTGRES_USER: Top
      POSTGRES_PASSWORD: 141713
      POSTGRES_DB: BabylonianGateDb
    
    ports:
      - "5432:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: